{
 "title": "GCP Asset Inventory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_ids",
    "query": "select distinct(project_id) from gcp_resources"
   },
   {
    "name": "regions",
    "query": "select distinct(CASE\n                    WHEN region != '' THEN region\n                    WHEN zone != '' THEN left(zone, -2)\n                    ELSE 'global'\n    END) as location\nfrom gcp_resources;"
   },
   {
    "name": "cq_tables",
    "query": "select distinct(cq_table) from gcp_resources;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*)\nfrom gcp_resources\nwhere project_id in (${project_ids})\n  and (CASE\n           WHEN region != '' THEN region\n           WHEN zone != '' THEN left(zone, -2)\n           ELSE 'global'\n    END) in (${regions})\n  and cq_table in (${cq_tables});"
    }
   ]
  },
  {
   "title": "Total Resource by Project",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*)\nfrom gcp_resources\nwhere (CASE\n           WHEN region != '' THEN region\n           WHEN zone != '' THEN left(zone, -2)\n           ELSE 'global'\n    END) in (${regions})\n  and cq_table in (${cq_tables})\ngroup by project_id\norder by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Region",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select (CASE\n            WHEN region != '' THEN region\n            WHEN zone != '' THEN left(zone, -2)\n            ELSE 'global'\n    END) as location,\n       count(*)\nfrom gcp_resources\nwhere (CASE\n           WHEN region != '' THEN region\n           WHEN zone != '' THEN left(zone, -2)\n           ELSE 'global'\n    END) in (${regions})\n  and project_id in (${project_ids})\n  and cq_table in (${cq_tables})\ngroup by location\norder by count desc;"
    }
   ]
  },
  {
   "title": "GCP Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select cq_id,\n       cq_table,\n       project_id,\n       (CASE\n            WHEN region != '' THEN region\n            WHEN zone != '' THEN left(zone, -2)\n            ELSE 'global'\n           END) as location,\n       id,\n       fetch_date\nfrom gcp_resources\nwhere project_id in (${project_ids})\n  and (CASE\n           WHEN region != '' THEN region\n           WHEN zone != '' THEN left(zone, -2)\n           ELSE 'global'\n    END) in (${regions})\n  and cq_table in (${cq_tables});"
    }
   ]
  },
  {
   "title": "Count by Resource Type",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select cq_table, count(*)\nfrom gcp_resources\nwhere project_id in (${project_ids})\n  and (CASE\n           WHEN region != '' THEN region\n           WHEN zone != '' THEN left(zone, -2)\n           ELSE 'global'\n    END) in (${regions})\n  and cq_table in (${cq_tables})\ngroup by cq_table\norder by count desc;"
    }
   ]
  },
  {
   "title": "Resources by Region",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 6, "y": 21 },
   "targets": [
    {
     "rawSql": "select CASE\n           WHEN region != '' THEN region\n           WHEN zone != '' THEN left(zone, -2)\n           ELSE 'global'\n           END as location, count(*)\nfrom gcp_resources\nwhere project_id in (${project_ids})\nand cq_table in (${cq_tables})\ngroup by location\norder by count desc;"
    }
   ]
  }
 ]
}